### ISSUE TITLE
GCP and SMB libs are required to be installed on peer even when not being used

### ISSUE THREAD

**Issue by alanpcs** [wholebuzz/fs#2]
Hi!

This lib has a quite great interface and usability when abstracting FSs, kudos for that :rocket: 
In my current work case, I am using only the following configs:
```
fileSystemAdapter = new AnyFileSystem([
    { urlPrefix: 's3://', fs: new S3FileSystem() },
    { urlPrefix: '', fs: new LocalFileSystem() },
  ]);
```

Even though I have installed the dependencies for those FSs mentioned in the README, when I try to use the lib I still get asked to add `@google-cloud/storage` and `@marsaud/smb2` and its dependencies.

dependencies installed so I could use S3 and LocalFS:
```
"@google-cloud/storage": "^5.20.5",
"@marsaud/smb2": "^0.18.0",
"@wholebuzz/fs": "^1.2.9",
"athena-express": "^7.1.5",
"aws-sdk": "^2.1139.0",
"fs-ext": "^2.0.0",
"glob": "^8.0.3",
"glob-stream": "^7.0.0",
```

**Comment by wholebuzz** [comment]
Thanks!  This is probably due to importing via index.js (which imports and exports all the implementations). The solution is to change e.g. `import { LocalFileSystem } from '@wholebuzz/fs'` to `import { LocalFileSystem } from '@wholebuzz/fs/lib/local'`. The example in the documentation has been updated to be more clear  https://github.com/wholebuzz/fs#example

**Comment by alanpcs** [comment]
Thanks for the clarification
